kits:
  "gladiator":
    name: "&6Gladiator"
    image: "textures/items/iron_sword.png"
    permission: "gladiator.kit.permission"
    cooldown: 60 #in seconds
    helmet: 0
    chestPlate: 0
    leggings: 0
    boots: 0
    items:
      "0":
        data: "1:0:1"
        enchantments:
          - ""
          - ""