kits:
  "gladiator":
    name: "&6Gladiator"
    image: "textures/items/iron_sword.png"
    permission: "gladiator.kit.permission"
    cooldown: 60 #in seconds
    helmet:
      data: "1:0:1"
      enchantments:
        - ""
        - ""
    chestPlate:
      data: "1:0:1"
      enchantments:
        - ""
        - ""
    leggings:
      data: "1:0:1"
      enchantments:
        - ""
        - ""
    boots:
      data: "1:0:1"
      enchantments:
        - ""
        - ""
    items:
      "0":
        data: "1:0:1"
        enchantments:
          - ""
          - ""